version: '3.4'

networks:
  frontend:
  backend:

services:
  mssqlserver:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ProductApi(!)
    ports:
      - "1449:1443"
    container_name: eventsqlserver
    networks:
      - backend
 
  tokensqlserver:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ProductApi(!)
    ports:
      - "1448:1443"
    container_name: eventtokensqlserver
    networks:
      - backend

  basket.data:
    image: redis
    ports:
      - "7050:6369"
    container_name: basketdata
    networks:
      - backend
 
  catalog:
    image: events/catalogapi
    build:
      context: .\ProductCatalogAPI
      dockerfile: Dockerfile
    environment:
      ConnectionString: "Data Source=mssqlserver;Initial Catalog=EventDb;User Id=sa;Password=ProductApi(!);Connect Timeout=30;"
      ExternalBaseUrl: http://localhost:7000
    ports:
      - "7000:80"
    container_name: eventcatalogapi
    networks:
      - frontend
      - backend
    depends_on:
      - mssqlserver

  webmvc:
    image: events/webmvc
    container_name: webshop
    build:
      context: .\WebMvc
      dockerfile: Dockerfile
    environment:
      EventUrl: http://catalog
      CartUrl: http://cart
      IdentityUrl: http://192.168.0.20:7800
      CallBackUrl: http://localhost:7500
    ports:
      - "7500:80"
    networks:
        - frontend
    depends_on:
      - catalog
      - tokenserver
      - cart

  tokenserver:
    image: events/tokenapi
    build:
      context: .\TokenServiceAPI
      dockerfile: Dockerfile
    environment:
      ConnectionString: "Data Source=tokensqlserver;Initial Catalog=TokenServiceDb;User Id=sa;Password=ProductApi(!);Connect Timeout=30;"
      MvcClient: http://localhost:7500
    ports:
      - "7800:80"
    container_name: eventtokenapi

    networks:
      - frontend
      - backend
    depends_on:
      - tokensqlserver

  cart:
    image: events/cartapi
    build:
      context: .\CartAPI
      dockerfile: Dockerfile
    environment:
      ASP.NETCORE_ENVIRONMENT: Development
      IdentityUrl: http://192.168.0.20:7800
      ConnectionString: basket.data
    ports:
      - "7010:80"
    container_name: eventscartapi
    networks:
      - frontend
      - backend
    depends_on:
      - tokenserver
      - basket.data


      

